apiVersion: nextcloud.lorikarikari.io/v1
kind: Nextcloud
metadata:
  labels:
    app.kubernetes.io/name: nextcloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: nextcloud-sample
spec:
  version: "29.0.8"
  replicas: 1
  admin:
    username: "myuser"
    secretRef:
      name: "custom-admin-secret"
      passwordKey: "password"
      usernameKey: "username"
  database:
    version: "16"
    storageSize: "8Gi"
